markdown: CommonMarkGhPages
commonmark:
  options: ["FOOTNOTES", "UNSAFE"]
  extensions: ["strikethrough", "autolink", "table"]
theme: minima
title: hogehoge
lang: ja
timezone: Asia/Tokyo
author:
  name: teramako
  email: terama@gmail.com
description: >-
  メモ置き場。

timezone: Asia/Tokyo
minima:
  date_format: "%Y-%m-%d"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

