markdown: CommonMarkGhPages
commonmark:
  options: ["FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table"]
theme: minima
title: hogehoge
lang: ja
author:
  name: teramako
  email: terama@gmail.com
description: >-
  メモ置き場。

minima:
  date_format: "%Y-%m-%d"
plugins:
  - jekyll-feed
  - jekyll-seo-tag

