services:
  app:
    image: jekyll/teramako:pages
    command: jekyll serve --watch --incremental --verbose
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - .:/srv/jekyll
    ports:
      - 4000:4000
