version: '3'
services:
  app:
    image: jekyll/jekyll:pages
    command: jekyll serve --force_polling
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - .:/srv/jekyll
    ports:
      - 4000:4000
